--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TheUtopianPlayz/P2E_NBT
build-by-default: true
branches:
- master
projects:
  P2E_NBT:
    path: ""
    icon: "resources/P2E.png"
...
