---
name: P2E_NBT
version: 0.0.1
main: TheUtopian\p2e_nbt\P2E_NBT
api: 3.11.0
commands:
  nbt:
    description: "Broadcasts the held items nbt in chat!"
    permission: nbt.cmd
permissions:
  nbt.cmd:
    default: op
...
